const UPDATE_TOKEN = "UPDATE_TOKEN";
const UPDATE_IS_LOGGED_IN = "UPDATE_IS_LOGGED_IN";
const UPDATE_KARAMKODU_ID = "UPDATE_KARAMKODU_ID";
const UPDATE_PLANT_STATUS = "UPDATE_PLANT_STATUS";
const UPDATE_ENVIRONMENT_FLAG = "UPDATE_ENVIRONMENT_FLAG";

export {
  UPDATE_TOKEN,
  UPDATE_IS_LOGGED_IN,
  UPDATE_KARAMKODU_ID,
  UPDATE_PLANT_STATUS,
  UPDATE_ENVIRONMENT_FLAG
};
