const BASE_URL = "http://localhost:8888";
const LOGIN_URL = BASE_URL + "/login";
const PROFILE_URL = BASE_URL + "/profile";
const TEAM_MEMBER_STATUS = BASE_URL + "/team/status";
const GET_PLANT_URL = BASE_URL + "/plant";
const REGISTER_PLANT_URL = BASE_URL + "/plant";
const GET_TEAM_MEMBERS_URL = BASE_URL + "/team/members";
const GET_TEAM_REQUESTS_URL = BASE_URL + "/team/requests";
const SUBMIT_ENVIRONMENT_REPORT_URL = BASE_URL + "/report/environment";
const SUBMIT_EDUCATION_REPORT_URL = BASE_URL + "/report/education";
const TEAM_REQUEST_UPDATE_URL = BASE_URL + "/team/request";

const VERIFY_USER_URL = BASE_URL + "/volunteer";
const JOIN_TEAM_AS_MEMBER_REQUEST_URL = BASE_URL + "/team/request/member";
const JOIN_TEAM_AS_LEADER_REQUEST_URL = BASE_URL + "/team/request/leader";
export {
  PROFILE_URL,
  BASE_URL,
  VERIFY_USER_URL,
  JOIN_TEAM_AS_MEMBER_REQUEST_URL,
  JOIN_TEAM_AS_LEADER_REQUEST_URL,
  LOGIN_URL,
  TEAM_MEMBER_STATUS,
  GET_PLANT_URL,
  REGISTER_PLANT_URL,
  GET_TEAM_MEMBERS_URL,
  SUBMIT_ENVIRONMENT_REPORT_URL,
  SUBMIT_EDUCATION_REPORT_URL,
  GET_TEAM_REQUESTS_URL,
  TEAM_REQUEST_UPDATE_URL
};
